id: I35F64B63
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 10:38:54.225295+00:00
last_modified: 2022-12-14 10:38:54.225301+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-047-001
  eft-text-version: 1.26.3 2020
  title: Toh_99-The_Blessed_One%27s_Wisdom_That_Leads_to_Infinite_Certainty-v2
bases:
  190B:
    source_metadata: null
    order: 1
    base_file: 190B.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
